### ISSUE TITLE
Need to parameterize Maximo REST Url's  API Context 

### ISSUE THREAD

**Issue by jswoveland** [geocortex/workflow-activities-maximo#22]
The current Create Service Request activity has the Maximo REST Url's API Context hardcoded to **oslc**.   
The Maximo SME at John Hopkins University said that when connecting to their production Maximo instance we will need to use **api** for the API Context (required for Single Sign On).

Recommendation:
Add an input param "API Context" to the Create Service Request activity, with a default value of **oslc**.

**Comment by jondandois** [comment]
@rcooney is this change available in the latest release? I am the client that Jon referenced in the original issue.  We just ran into this today when attempting to move to prod. Thanks!

**Comment by rcooney** [comment]
@jondandois it was supposed to be, but it seems the release failed. I'll look into that now.

**Comment by jondandois** [comment]
Thanks!  Will take a look!

**Comment by jondandois** [comment]
We're running it on-prem, I was able to build and see the `context` input the activities. thanks.

**Comment by rcooney** [comment]
`v0.5.1` is now published and contains the changes.
